In [ ]:
#Q1 Create an empty 3x3 matrix and then fill it with a value 2. Display both the empty and filled matrices.
import numpy as np
emptyarrwithzeros=np.zeros([3,3])
print("3x3 Array With np.zeros \n",emptyarrwithzeros)
emptyarrwithempty=np.empty([3,3])
print("3x3 Array with np.empty \n",emptyarrwithempty)
#
# Assign value 2 to each element
#

In [ ]:
#Q2. Write a program to test each element if they are complex number, real number of a given array. 
#Also test whether a given number is a scalar type or not

In [ ]:
#Q3. Write a program to create a 4x4 array with random values, 
#now create a new array from the same array by swapping first and last rows

In [4]:
#Q4. Write a program to multiply two given arrays of the same size element-by-element.
import numpy as np
array1=np.array([[2,2,2],[3,3,3]])
array2=np.array([[4,4,4],[5,5,5]])
multi=np.multiply(array1,array2)
print(multi)

[[ 8  8  8]
 [15 15 15]]


In [7]:
#Q5. Write a program to get all the unique elements of an array.
array=[11,11,12,12,13,13,14,14,15]
array=np.array(array)
print(array.ndim,type(array))
uniq=np.unique(array)
print(uniq)

1 <class 'numpy.ndarray'>
[11 12 13 14 15]


In [8]:
#Q6. Write a program to find the union of two arrays.
#Union will return the unique, sorted array of values that are in either of the two input arrays.
array1=[1,11,22,44,66,88]
array2=[11,33,44,55,77]
array1=np.array(array1)
array2=np.array(array2)
uniarr=np.union1d(array1,array2)
print(uniarr)



[ 1 11 22 33 44 55 66 77 88]


In [5]:
#Q7. Create 2 arrays of size 5
#a. for length
#b. for breadth
#calculate the area and volume of the rectangle. Also calculate the variance and standard deviation.
import numpy as np
a=np.array([2,2,2])
b=np.array([3,3,3])
h=np.array([1,1,1])
area=np.multiply(a,b)
print("area :",area)
print(type(area))
print(area.ndim)
volume=np.multiply(a,b,h)
print("Volume :",volume)
print(type(volume))
print(volume.ndim)


area : [6 6 6]
<class 'numpy.ndarray'>
1
Volume : [6 6 6]
<class 'numpy.ndarray'>
1
