<a href="https://colab.research.google.com/github/njoshi19/NSArrowsAssignment/blob/main/C513Mar22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpay is Numerical Python
Installing Numpy is necessary

In [ ]:
#Installing numpy
import numpy as np
pricelist=[10,20,30,40,50]
print(type(pricelist))
print(pricelist)
pricearray=np.array(pricelist)
print(type(pricearray))
print(pricearray)

<class 'list'>
[10, 20, 30, 40, 50]
<class 'numpy.ndarray'>
[10 20 30 40 50]


In [ ]:
#Creating One Dimensional Array
# np is library imported numpy
# random (first) is random co
np.random.random(size=10)

array([0.90149974, 0.55983398, 0.64823746, 0.68577247, 0.04280349,
       0.03821431, 0.2552519 , 0.10712727, 0.77763732, 0.51840047])

In [ ]:
np.random.rand(2,3)

array([[0.09900407, 0.10178492, 0.17518762],
       [0.15940027, 0.63001504, 0.31523072]])

In [ ]:
np.random.randn(2,3)

array([[ 1.12389461,  0.47972505,  0.96177584],
       [ 0.01031524, -0.66102888, -0.60865496]])

In [ ]:
np.random.randint(5,15)

6

In [ ]:
np.random.randint(15,50,5)

array([25, 28, 28, 49, 32])

In [ ]:
oddnums=np.arange(start=9,stop=99,step=2)
print(oddnums)
print(type(oddnums))

[ 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55
 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97]
<class 'numpy.ndarray'>


In [ ]:
nums=np.linspace(start=9,stop=99,num=10)
print(nums)
print(type(nums))

[ 9. 19. 29. 39. 49. 59. 69. 79. 89. 99.]
<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
matrix=np.empty((3,3),dtype=int)
print(matrix)
print(type(matrix))

[[     94022561510448                  41          4294967295]
 [3343197489899464494 7593682930701921379 8515877477639614823]
 [7237088288518385202 8315181416901143653                 116]]
<class 'numpy.ndarray'>


In [ ]:
matrix=np.full((3,3),fill_value=15)
print(matrix)

[[15 15 15]
 [15 15 15]
 [15 15 15]]


In [ ]:
matrix=np.identity(5)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
tools=np.array([("Screw Driver","Scews","Nuts"),(150,10,23)])
print(tools)
print("Shape of the tool",tools.shape)

[['Screw Driver' 'Scews' 'Nuts']
 ['150' '10' '23']]
Shape of the tool (2, 3)


In [ ]:
prodweight=np.array([(1,2,3),(50,2.0,20.0)])
print(prodweight)
print("Type Of Elements In Arrary Is :",type(prodweight))
print("Type Of Elements In Arrary Is :",prodweight.dtype)

[[ 1.  2.  3.]
 [50.  2. 20.]]
Type Of Elements In Arrary Is : <class 'numpy.ndarray'>
Type Of Elements In Arrary Is : float64


In [ ]:
prodweight=np.array([(1,2,3),(50,2.0,20.0)])
print(prodweight)
print("Type Of Elements In Arrary Is :",type(prodweight))
print("Type Of Elements In Arrary Is :",prodweight.ndim)

[[ 1.  2.  3.]
 [50.  2. 20.]]
Type Of Elements In Arrary Is : <class 'numpy.ndarray'>
Type Of Elements In Arrary Is : 2


In [ ]:
employee=np.array([("Adam",19),("Steve",21),("Mark",18),("Thomas",22)])
print(employee)
employeereshape=employee.reshape(8,1)
print("\n")
print(employeereshape)

[['Adam' '19']
 ['Steve' '21']
 ['Mark' '18']
 ['Thomas' '22']]


[['Adam']
 ['19']
 ['Steve']
 ['21']
 ['Mark']
 ['18']
 ['Thomas']
 ['22']]


In [ ]:
datascientists=np.array([("Adam",19),("Steve",21),("Mark",18),("Thomas",22)])
print("First Element :",datascientists[0])
print("Last Element :",datascientists[-1])
print("Age of Data Scientist at index position 1:",datascientists[1][1])
print("Age of Data Scientist at index position Last :",datascientists[-1][1])

First Element : ['Adam' '19']
Last Element : ['Thomas' '22']
Age of Data Scientist at index position 1: 21
Age of Data Scientist at index position Last : 22


In [ ]:
age=np.array([73,68,55.5,72,66])
print("3rd and 4th element :",age[2:4])
print("Every 2nd Element :",age[0::2])

3rd and 4th element : [55.5 72. ]
Every 2nd Element : [73.  55.5 66. ]


In [ ]:
#Creating 2D Arrary
weights=np.array([(74,55,68),(48,56,64)])
print("Original Array :",weights)
print("\n Elements in the first row and first two columns :",weights[0,0:2])
print("\n Elements in the second row and last two columns :",weights[1,1:])

Original Array : [[74 55 68]
 [48 56 64]]

 Elements in the first row and first two columns : [74 55]

 Elements in the second row and last two columns : [56 64]


In [ ]:
#addition and substraction
oddnum=np.array([3,5,7,9])
evennum=np.array([8,12,22,10])
print("Odd Nums",oddnum)
print("Even Nums",evennum)
sum=oddnum+evennum
print("add value :",sum)
sub=oddnum-evennum
print("subtracted value :",sub)

Odd Nums [3 5 7 9]
Even Nums [ 8 12 22 10]
add value : [11 17 29 19]
subtracted value : [ -5  -7 -15  -1]


In [ ]:
numarray=np.array([1,2,3,4,5])
print("Product Result :",numarray*5)

Product Result : [ 5 10 15 20 25]


In [ ]:
m1=np.array([[1,2,3],[4,-3,2]])
m2=np.array([[4,0,1],[2,3,0]])
print(m1)
print(m2)
prod=m1*m2
print("Hadamard Product :\n",prod)

[[ 1  2  3]
 [ 4 -3  2]]
[[4 0 1]
 [2 3 0]]
Hadamard Product :
 [[ 4  0  3]
 [ 8 -9  0]]


In [ ]:
m1=np.array([[1,2,3],[4,-3,2]])
m2=np.array([[4,0],[1,2],[3,0]])
print(m1)
print(m2)
prod=m1.dot(m2)
print(prod)

[[ 1  2  3]
 [ 4 -3  2]]
[[4 0]
 [1 2]
 [3 0]]
[[15  4]
 [19 -6]]


In [ ]:
salary=np.array([100000,20000,45000,85000,19000])
print("Maxmimum Salary    ",max(salary))
print("Minimum Salary     ",min(salary))
print("Variance of Salary ",salary.var())
print("Standard Deviation of the salaries ",salary.std())


Maxmimum Salary     100000
Minimum Salary      19000
Variance of Salary  1107760000.0
Standard Deviation of the salaries  33283.028708337224


In [ ]:
sides=np.array([10,5,20,25,30])
print("Area of the square   :",np.square(sides))
print("Volume of the square :",np.power(sides,3))



Area of the square   : [100  25 400 625 900]
Volume of the square : [ 1000   125  8000 15625 27000]


In [ ]:
#Transposing - Very Important
datascientists=np.array([("Adam",19),("Steve",21),("Mark",18),("Thomas",22)])
print("\n Original Matrix   :\n",datascientists)
print("\n Transposed Matrix :\n",np.transpose(datascientists))


 Original Matrix   :
 [['Adam' '19']
 ['Steve' '21']
 ['Mark' '18']
 ['Thomas' '22']]

 Transposed Matrix :
 [['Adam' 'Steve' 'Mark' 'Thomas']
 ['19' '21' '18' '22']]


In [ ]:
from typing_extensions import Concatenate
from numpy.core.multiarray import concatenate
#Concatenation of matrices
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10,11,12])
concatearray=np.concatenate([array1,array2])
print(concatearray)
employees=np.array([["Navin",20],["Amey",22],["Jessica",30]])
consultants=np.array([["Rajiv",38],["Suresh",35]])
totalemp=np.concatenate([employees,consultants])
print(totalemp)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[['Navin' '20']
 ['Amey' '22']
 ['Jessica' '30']
 ['Rajiv' '38']
 ['Suresh' '35']]


In [ ]:
#Flattening Array
numarray=np.array([[1,2,3,4],[5,6,7,8]])
print("Original Array \n",numarray)
print("Flattenend Array \n",np.ndarray.flatten(numarray))

Original Array 
 [[1 2 3 4]
 [5 6 7 8]]
Flattenend Array 
 [1 2 3 4 5 6 7 8]


In [ ]:
menus=np.array([["Grilled Samosa","Veg Salad","Dal Makhani"],[350,250,200]])
print("The Array of Menu is ",menus.ndim,"dimensional array \n")
for menu in menus:
  print(menu)

The Array of Menu is  2 dimensional array 

['Grilled Samosa' 'Veg Salad' 'Dal Makhani']
['350' '250' '200']


In [ ]:
menus=np.array([["Grilled Samosa","Veg Salad","Dal Makhani"],[350,250,200]])
print("The Array of Menu is ",menus.ndim,"dimensional array \n")
for menu in menus:
  for element in menu:
    print(element)

The Array of Menu is  2 dimensional array 

Grilled Samosa
Veg Salad
Dal Makhani
350
250
200
